name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: build
          domain: mm2bc.ustc-zzzz.net
